#!/usr/bin/env bash

install-posh() {
	curl -s https://ohmyposh.dev/install.sh | bash -s
	oh-my-posh font install meslo
}

export PATH=$PATH:/home/thomas/.local/bin
if [[ ! -x "$(command -v oh-my-posh)" ]]; then
	install-posh
fi
