#!/usr/bin/env bash

# Detect OS
detect-os() {
	grep ^ID /etc/os-release | cut -d = -f 2
}

# Run install script
# Args:
#	OS ID
install() {
	local files=$(find ".install/$1" -type f)
	while IFS= read -r file; do
		. "$file"
	done <<< $files
}

main() {
	local os=$(detect-os)

	install $os
}

main
