#!/usr/bin/env bash

# Detect OS
detect-os() {
	grep ^ID /etc/os-release | cut -d = -f 2
}

# Run install script
# Args:
#	OS ID
install() {
	local files=$(find ".install/$1" -type f)
	local failed_packages=
	while IFS= read -r file; do
		. "$file"
		if [[ $? -ne 0 ]]; then
			failed_packages="$failed_packages;$(echo $file | cut -d / -f 3 | cut -d _ -f 2)"
		fi
	done <<< $files
	if [[ -n failed_packages ]]; then
		echo "The following packages failed to install:"
		echo "$failed_packages" | sed -s "s/;/\n/g"
	fi
}

main() {
	local os=$(detect-os)

	install $os
}

main
