#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

PACKAGES=$(ls -d */ | cut -f 1 -d '/')

copy-home() {
	local files=$(find $1 -type f)
	while IFS= read -r file; do
		cp $file $(sed -n "s|[^/]*|$HOME|p" <<< $file)
	done <<< $files
}

# Stow packages
# Args:
#	Packages to create symlinks for
stow-packages() {
	if [[ "$OSTYPE" = "linux-gnu" ]]; then
		while IFS= read -r pkg; do
			stow -R "$pkg"
		done <<< $1
	elif [[ "$OSTYPE" = "cygwin" || "$OSTYPE" = "msys" ]]; then
		while IFS= read -r pkg; do
			copy-home "$pkg"
		done <<< $1
	else
		echo "Operating System $OSTYPE not implemented" >&2
	fi
}

main() {
	# Stow packages
	stow-packages "$PACKAGES"

	# Reload .bashrc
	source ~/.bashrc
}

main
