#!/usr/bin/env bash

install-unzip() {
	sudo apt install unzip
}

install-posh() {
	curl -s https://ohmyposh.dev/install.sh | bash -s

	oh-my-posh font install meslo
}

cleanup() {
	return 1
}

trap cleanup ERR

if [[ ! -x "$(command -v unzip)" ]]; then
	install-unzip
fi

export PATH="$PATH:$HOME/.local/bin"
if [[ ! -x "$(command -v oh-my-posh)" ]]; then
	install-posh
fi
