#!/usr/bin/env bash

install-neovim() {
	sudo add-apt-repository ppa:neovim-ppa/stable -y
	sudo apt-get update -y
	sudo apt-get install neovim -y
}

if [[ ! -x "$(command -v nvim)" ]]; then
	install-neovim
fi
