#!/usr/bin/env bash

copy-package() {
	local files=$(find $1 -type f)
	local target=$2
	while IFS= read -r file; do
		cp $file $(sed -n "s|[^/]*|${targets[pkg]}|p" <<< $file)
	done <<< $files
}

stow-package() {
	local pkg=$1
	local target=$2

	case "$OSTYPE" in 
		"linux-gnu")
			stow "$pkg" -R -d packages -t "$target"
			;;
		"cygwin"|"msys")
			copy-package "$pkg" "$target"
			;;
		*)
			echo "Operating System $OSTYPE not implemented" >&2
			exit 1
			;;
	esac
}

# Stow packages
# Args:
#	Packages to create symlinks for
stow-packages() {
	local packages=$1
	declare -n targets=$2
	case "$OSTYPE" in 
		"linux-gnu"|"cygwin"|"msys")
			;;
		*) 
			echo "Operating System $OSTYPE not implemented" >&2
			exit 1
			;;
	esac

	while IFS= read -R -d pkg; do
		stow-package "$pkg" "${targets[pkg]}"
	done <<< $packages
}
