#!/usr/bin/env bash

install-unzip() {
	echo "Installing unzip"
	sudo apt install unzip
}

install-posh() {
	echo "Installing oh-my-posh"
	curl -s https://ohmyposh.dev/install.sh | bash -s
	export PATH=$PATH:/home/thomas/.local/bin

	echo "Installing Meslo Nerd Font"
	oh-my-posh font install meslo
}

cleanup() {
	return 1
}

trap cleanup ERR

install-unzip
install-posh

